# Generated by Django 3.2.9 on 2022-01-07 17:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220106_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 7, 17, 52, 10, 314819, tzinfo=utc)),
        ),
    ]
