# Generated by Django 3.2.9 on 2022-01-08 11:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20220108_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 8, 11, 19, 50, 590828, tzinfo=utc)),
        ),
    ]
